# Generated by Django 3.1.5 on 2021-01-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contactNo', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=200)),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='itemsTemp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('Description', models.TextField(max_length=400)),
                ('DoingBusinessAs', models.TextField(max_length=200)),
                ('StreetAddress', models.TextField(max_length=400)),
                ('City', models.TextField(max_length=400)),
                ('subcatid', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Amount', models.FloatField()),
                ('Description', models.TextField(max_length=400)),
                ('DoingBusinessAs', models.TextField(max_length=200)),
                ('StreetAddress', models.TextField(max_length=400)),
                ('City', models.TextField(max_length=400)),
                ('subcatid', models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
    ]
