# Generated by Django 3.1.6 on 2021-02-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='subcatid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
        migrations.AlterField(
            model_name='itemstemp',
            name='subcatid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subcategory'),
        ),
    ]
