# Generated by Django 3.1.6 on 2021-02-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210214_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users'),
        ),
        migrations.AlterField(
            model_name='items',
            name='subcatid',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory'),
        ),
        migrations.AlterField(
            model_name='itemstemp',
            name='subcatid',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='catid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.users'),
        ),
    ]
