# Generated by Django 3.1.6 on 2021-02-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210226_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='uid',
        ),
    ]
