# Generated by Django 3.1.6 on 2021-02-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210228_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
    ]
